- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/leo_marsyard/model/aries/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/world/leo_marsyard/pose/info"
  gz_topic_name: "/world/leo_marsyard/pose/info"
  ros_type_name: "geometry_msgs/msg/PoseArray"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "/tf"
  gz_topic_name: "/model/aries/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS


- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/model/aries/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ


- ros_topic_name: "/camera/color/image_raw"
  gz_topic_name:  "/camera/color/image_raw"
  ros_type_name:  "sensor_msgs/msg/Image"
  gz_type_name:   "gz.msgs.Image"
  direction:      GZ_TO_ROS


- ros_topic_name: "/camera/color/camera_info"
  gz_topic_name:  "/camera/color/camera_info"
  ros_type_name:  "sensor_msgs/msg/CameraInfo"
  gz_type_name:   "gz.msgs.CameraInfo"
  direction:      GZ_TO_ROS

- ros_topic_name: "/camera/depth/camera_info"
  gz_topic_name:  "/camera/depth/camera_info"
  ros_type_name:  "sensor_msgs/msg/CameraInfo"
  gz_type_name:   "gz.msgs.CameraInfo"
  direction:      GZ_TO_ROS

- ros_topic_name: "/camera/depth/image_rect_raw"
  gz_topic_name:  "/camera/depth/image_rect_raw"
  ros_type_name:  "sensor_msgs/msg/Image"
  gz_type_name:   "gz.msgs.Image"
  direction:      GZ_TO_ROS

- ros_topic_name: "/camera/depth/image_rect_raw/points"
  gz_topic_name:  "/camera/depth/image_rect_raw/points"
  ros_type_name:  "sensor_msgs/msg/PointCloud2"
  gz_type_name:   "gz.msgs.PointCloudPacked"
  direction:      GZ_TO_ROS

- ros_topic_name: "/camera/infra1/camera_info"
  gz_topic_name:  "/camera/infra1/camera_info"
  ros_type_name:  "sensor_msgs/msg/CameraInfo"
  gz_type_name:   "gz.msgs.CameraInfo"
  direction:      GZ_TO_ROS

- ros_topic_name: "/camera/infra1/image_rect_raw"
  gz_topic_name:  "/camera/infra1/image_rect_raw"
  ros_type_name:  "sensor_msgs/msg/Image"
  gz_type_name:   "gz.msgs.Image"
  direction:      GZ_TO_ROS

- ros_topic_name: "/camera/infra2/camera_info"
  gz_topic_name:  "/camera/infra2/camera_info"
  ros_type_name:  "sensor_msgs/msg/CameraInfo"
  gz_type_name:   "gz.msgs.CameraInfo"
  direction:      GZ_TO_ROS

- ros_topic_name: "/camera/infra2/image_rect_raw"
  gz_topic_name:  "/camera/infra2/image_rect_raw"
  ros_type_name:  "sensor_msgs/msg/Image"
  gz_type_name:   "gz.msgs.Image"
  direction:      GZ_TO_ROS







# LaserScan (nice for a quick sanity check in RViz)
- ros_topic_name: "/scan"
  gz_topic_name: "/lidar"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# 3D point cloud
- ros_topic_name: "/points"
  gz_topic_name: "/lidar/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

# (Recommended) Odometry from DiffDrive → ROS
- ros_topic_name: "/odom"
  gz_topic_name: "/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS







# IMU data
- ros_topic_name: "/imu"
  gz_topic_name: "/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS



- ros_topic_name: "/world/leo_marsyard/light_config"
  gz_topic_name: "/world/leo_marsyard/light_config"
  ros_type_name: "ros_gz_interfaces/msg/Light"
  gz_type_name: "gz.msgs.Light"
  direction: GZ_TO_ROS

# Base velocity commands (Twist) -> DiffDrive
- ros_topic_name: "/model/aries/cmd_vel"
  gz_topic_name: "/model/aries/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/aries/L_Rocker_Joint/cmd_pos"
  gz_topic_name:  "/model/aries/joint/L_Rocker_Joint/cmd_pos"
  ros_type_name:  "std_msgs/msg/Float64"
  gz_type_name:   "gz.msgs.Double"
  direction:      ROS_TO_GZ

- ros_topic_name: "/aries/R_Rocker_Joint/cmd_pos"
  gz_topic_name:  "/model/aries/joint/R_Rocker_Joint/cmd_pos"
  ros_type_name:  "std_msgs/msg/Float64"
  gz_type_name:   "gz.msgs.Double"
  direction:      ROS_TO_GZ

- ros_topic_name: "/aries/L_Boggie_Joint/cmd_pos"
  gz_topic_name:  "/model/aries/joint/L_Boggie_Joint/cmd_pos"
  ros_type_name:  "std_msgs/msg/Float64"
  gz_type_name:   "gz.msgs.Double"
  direction:      ROS_TO_GZ
  
- ros_topic_name: "/aries/R_Boggie_Joint/cmd_pos"
  gz_topic_name:  "/model/aries/joint/R_Boggie_Joint/cmd_pos"
  ros_type_name:  "std_msgs/msg/Float64"
  gz_type_name:   "gz.msgs.Double"
  direction:      ROS_TO_GZ

- ros_topic_name: "/aries/arm_shoulder_joint/cmd_pos"
  gz_topic_name:  "/model/aries/joint/arm_shoulder_joint/cmd_pos"
  ros_type_name:  "std_msgs/msg/Float64"
  gz_type_name:   "gz.msgs.Double"
  direction:      ROS_TO_GZ

- ros_topic_name: "/aries/arm_elbow_joint/cmd_pos"
  gz_topic_name:  "/model/aries/joint/arm_elbow_joint/cmd_pos"
  ros_type_name:  "std_msgs/msg/Float64"
  gz_type_name:   "gz.msgs.Double"
  direction:      ROS_TO_GZ 

- ros_topic_name: "/aries/arm_gripper_joint/cmd_pos"
  gz_topic_name:  "/model/aries/joint/arm_gripper_joint/cmd_pos"
  ros_type_name:  "std_msgs/msg/Float64"
  gz_type_name:   "gz.msgs.Double"
  direction:      ROS_TO_GZ

- ros_topic_name: "/aries/arm_base_joint/cmd_pos"
  gz_topic_name:  "/model/aries/joint/arm_base_joint/cmd_pos"
  ros_type_name:  "std_msgs/msg/Float64"
  gz_type_name:   "gz.msgs.Double"
  direction:      ROS_TO_GZ




